// <auto-generated />
using System;
using ERPiFinansijeData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPiFinansijeData.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260725154743_DodajLegacyDbfKolone")]
    partial class DodajLegacyDbfKolone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ERPiFinansijeData.Models.Artikal", b =>
                {
                    b.Property<int>("ArtikalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barkod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KlasifikacionaSifra")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pakovanje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("Selektovan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarifniBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtikalId");

                    b.HasIndex("SifraArtikla");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FirmaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Firme");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Kalkulacija", b =>
                {
                    b.Property<int>("KalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKalkulacije")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojOtpremnice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumOtpremnice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarzaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PoreskaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("Porez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Razlika")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraDobavljaca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SvegaNabavno")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SvegaTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportniTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportnoOsiguranje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TroskoviUskladistenja")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UtovarIstovar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("KalkulacijaId");

                    b.HasIndex("BrojKalkulacije");

                    b.ToTable("Kalkulacije");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.KamatnaStopa", b =>
                {
                    b.Property<int>("KamatnaStopaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GodisnjaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("KamatnaStopaId");

                    b.HasIndex("DatumOd");

                    b.ToTable("KamatneStope");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.KarticaKonta", b =>
                {
                    b.Property<int>("KarticaKontaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojNaloga")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNaloga")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpisPromeneKod")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TekuceDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TekucePotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("KarticaKontaId");

                    b.HasIndex("BrojKonta");

                    b.ToTable("KarticeKonta");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSintetika")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klasa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivKonta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulica")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaKonta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KontoId");

                    b.HasIndex("BrojKonta")
                        .IsUnique();

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PoslednjaPrijava")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("KorisnikId");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            ImeIPrezime = "Administrator",
                            IsActive = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "PBKDF2$100000$CnYWiALqycqWTueq6ayEvQ==$hvm9e8z3e+KVeRsego3azOuoTp3q64deikPgUB9/D4o=",
                            Uloga = "Administrator"
                        });
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Magacin", b =>
                {
                    b.Property<int>("MagacinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivMagacina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OdgovornoLice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaMagacina")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MagacinId");

                    b.ToTable("Magacini");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.MaloprodajnaKalkulacija", b =>
                {
                    b.Property<int>("MaloprodajnaKalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKalkulacije")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojOtpremnice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumOtpremnice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrgovinskiKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Porez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatPri")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Razlika")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraDobavljaca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaDaje")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaPrima")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SifraProdavnice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SvegaNabavno")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SvegaTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportniTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportnoOsiguranje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TroskoviUskladistenja")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UtovarIstovar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaloprodajnaKalkulacijaId");

                    b.HasIndex("BrojKalkulacije");

                    b.ToTable("MaloprodajneKalkulacije");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.MaterijalnaKartica", b =>
                {
                    b.Property<int>("MaterijalnaKarticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CenaIzlaz")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("DatumPromene")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Izlaz")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("OpisPromene")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stanje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Ulaz")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaterijalnaKarticaId");

                    b.HasIndex("SifraMagacina", "SifraArtikla");

                    b.ToTable("MaterijalneKartice");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Nalog", b =>
                {
                    b.Property<int>("NalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumKnjiženja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNaloga")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VrstaNaloga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("NalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("Nalozi");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraPartnera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.HasIndex("SifraPartnera");

                    b.ToTable("Partneri");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.PrimopredajaNalog", b =>
                {
                    b.Property<int>("PrimopredajaNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacinaDaje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaPrima")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PrimopredajaNalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("PrimopredajaNalozi");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.PrimopredajaStavka", b =>
                {
                    b.Property<int>("PrimopredajaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PrimopredajaNalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PrimopredajaStavkaId");

                    b.HasIndex("PrimopredajaNalogId");

                    b.ToTable("PrimopredajaStavke");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.StavkaNaloga", b =>
                {
                    b.Property<int>("StavkaNalogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PromenaKod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValutaDospela")
                        .HasColumnType("TEXT");

                    b.HasKey("StavkaNalogaId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("StavkeNaloga");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.TrebovanjeNalog", b =>
                {
                    b.Property<int>("TrebovanjeNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TrebovanjeNalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("TrebovanjeNalozi");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.TrebovanjeStavka", b =>
                {
                    b.Property<int>("TrebovanjeStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("KontoTroska")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrebovanjeNalogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrebovanjeStavkaId");

                    b.HasIndex("TrebovanjeNalogId");

                    b.ToTable("TrebovanjeStavke");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.UlazNalog", b =>
                {
                    b.Property<int>("UlazNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UlazNalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("UlazNalozi");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.UlazStavka", b =>
                {
                    b.Property<int>("UlazStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UlazNalogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UlazStavkaId");

                    b.HasIndex("UlazNalogId");

                    b.ToTable("UlazStavke");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.PrimopredajaStavka", b =>
                {
                    b.HasOne("ERPiFinansijeData.Models.PrimopredajaNalog", "PrimopredajaNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("PrimopredajaNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimopredajaNalog");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.StavkaNaloga", b =>
                {
                    b.HasOne("ERPiFinansijeData.Models.Nalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPiFinansijeData.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.TrebovanjeStavka", b =>
                {
                    b.HasOne("ERPiFinansijeData.Models.TrebovanjeNalog", "TrebovanjeNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("TrebovanjeNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrebovanjeNalog");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.UlazStavka", b =>
                {
                    b.HasOne("ERPiFinansijeData.Models.UlazNalog", "UlazNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("UlazNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UlazNalog");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.Nalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.PrimopredajaNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.TrebovanjeNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiFinansijeData.Models.UlazNalog", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
