// <auto-generated />
using System;
using AccountingData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingData.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260801213957_DodajPfrSimulatorMod")]
    partial class DodajPfrSimulatorMod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("AccountingData.Models.Artikal", b =>
                {
                    b.Property<int>("ArtikalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barkod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KlasifikacionaSifra")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pakovanje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool>("Selektovan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarifniBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtikalId");

                    b.HasIndex("SifraArtikla");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("AccountingData.Models.BlagajnickiNalog", b =>
                {
                    b.Property<int>("BlagajnickiNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKontaProtu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Svrha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UplatilacIsplatilac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VrstaBlagajne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VrstaNaloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlagajnickiNalogId");

                    b.ToTable("BlagajnickiNalozi");
                });

            modelBuilder.Entity("AccountingData.Models.DokumentPrilog", b =>
                {
                    b.Property<int>("DokumentPrilogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPriloga")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivFajla")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("PutanjaFajla")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RacunOtpremnicaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("VelicinaBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("DokumentPrilogId");

                    b.HasIndex("KalkulacijaId");

                    b.HasIndex("NalogId");

                    b.HasIndex("RacunOtpremnicaId");

                    b.ToTable("DokumentiPrilozi");
                });

            modelBuilder.Entity("AccountingData.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JbkjsBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrKasirName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrPacKod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PfrSimulatorMod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PfrUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefApiKey")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefEnvironment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FirmaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Firme");
                });

            modelBuilder.Entity("AccountingData.Models.FiskalniRacunLog", b =>
                {
                    b.Property<int>("FiskalniRacunLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceCounter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kasir")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RacunOtpremnicaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJsonResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SdcDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("FiskalniRacunLogId");

                    b.ToTable("FiskalniRacuniLog");
                });

            modelBuilder.Entity("AccountingData.Models.Kalkulacija", b =>
                {
                    b.Property<int>("KalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojKalkulacije")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojOtpremnice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumOtpremnice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarzaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PoreskaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("Porez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Razlika")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraDobavljaca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SvegaNabavno")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SvegaTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportniTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportnoOsiguranje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TroskoviUskladistenja")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UtovarIstovar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("KalkulacijaId");

                    b.HasIndex("BrojKalkulacije");

                    b.ToTable("Kalkulacije");
                });

            modelBuilder.Entity("AccountingData.Models.KalkulacijaStavka", b =>
                {
                    b.Property<int>("KalkulacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PorezIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RazlikaIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Troskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("KalkulacijaStavkaId");

                    b.HasIndex("KalkulacijaId");

                    b.ToTable("KalkulacijaStavke");
                });

            modelBuilder.Entity("AccountingData.Models.KamatnaStopa", b =>
                {
                    b.Property<int>("KamatnaStopaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GodisnjaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("KamatnaStopaId");

                    b.HasIndex("DatumOd");

                    b.ToTable("KamatneStope");
                });

            modelBuilder.Entity("AccountingData.Models.KarticaKonta", b =>
                {
                    b.Property<int>("KarticaKontaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojNaloga")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNaloga")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpisPromeneKod")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TekuceDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TekucePotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("KarticaKontaId");

                    b.HasIndex("BrojKonta");

                    b.ToTable("KarticeKonta");
                });

            modelBuilder.Entity("AccountingData.Models.Kompenzacija", b =>
                {
                    b.Property<int>("KompenzacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera2")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera3")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Partner2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Partner3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupanIznosKompenzacije")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vrsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("KompenzacijaId");

                    b.ToTable("Kompenzacije");
                });

            modelBuilder.Entity("AccountingData.Models.KompenzacijaStavka", b =>
                {
                    b.Property<int>("KompenzacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosFakture")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPreostalo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosZaKompenzaciju")
                        .HasColumnType("TEXT");

                    b.Property<int>("KompenzacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StavkaNalogaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KompenzacijaStavkaId");

                    b.HasIndex("KompenzacijaId");

                    b.ToTable("KompenzacijeStavke");
                });

            modelBuilder.Entity("AccountingData.Models.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSintetika")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klasa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivKonta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulica")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaKonta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KontoId");

                    b.HasIndex("BrojKonta")
                        .IsUnique();

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("AccountingData.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PoslednjaPrijava")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("KorisnikId");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            ImeIPrezime = "Administrator",
                            IsActive = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "PBKDF2$100000$IxpGjzsTHvV0x7fZq6RdJQ==$6ERduoiJeJ9Iwc5bF56gYD0r3MqcFCWBYyw8XTHQ3u4=",
                            Uloga = "Administrator"
                        });
                });

            modelBuilder.Entity("AccountingData.Models.KursnaListaStavka", b =>
                {
                    b.Property<int>("KursnaListaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jedinica")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KupovniKurs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("NazivValute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProdavniKurs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SrednjiKurs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("ValutaOznaka")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValutaSifra")
                        .HasColumnType("INTEGER");

                    b.HasKey("KursnaListaStavkaId");

                    b.ToTable("KursneListeStavke");
                });

            modelBuilder.Entity("AccountingData.Models.Magacin", b =>
                {
                    b.Property<int>("MagacinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivMagacina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OdgovornoLice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaMagacina")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MagacinId");

                    b.ToTable("Magacini");
                });

            modelBuilder.Entity("AccountingData.Models.MaloprodajnaKalkulacija", b =>
                {
                    b.Property<int>("MaloprodajnaKalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojKalkulacije")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojOtpremnice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumOtpremnice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrgovinskiKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarzaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PoreskaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("Porez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatPri")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Razlika")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraDobavljaca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaDaje")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaPrima")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SifraProdavnice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SvegaNabavno")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SvegaTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportniTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportnoOsiguranje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TroskoviUskladistenja")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UtovarIstovar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaloprodajnaKalkulacijaId");

                    b.HasIndex("BrojKalkulacije");

                    b.ToTable("MaloprodajneKalkulacije");
                });

            modelBuilder.Entity("AccountingData.Models.MaloprodajnaKalkulacijaStavka", b =>
                {
                    b.Property<int>("MaloprodajnaKalkulacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaloprodajnaKalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PorezIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RazlikaIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Troskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaloprodajnaKalkulacijaStavkaId");

                    b.HasIndex("MaloprodajnaKalkulacijaId");

                    b.ToTable("MaloprodajnaKalkulacijaStavke");
                });

            modelBuilder.Entity("AccountingData.Models.Materijal", b =>
                {
                    b.Property<int>("MaterijalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pakovanje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MaterijalId");

                    b.HasIndex("SifraArtikla");

                    b.ToTable("Materijali");
                });

            modelBuilder.Entity("AccountingData.Models.MaterijalnaKartica", b =>
                {
                    b.Property<int>("MaterijalnaKarticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CenaIzlaz")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("DatumPromene")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Izlaz")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("OpisPromene")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stanje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Ulaz")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaterijalnaKarticaId");

                    b.HasIndex("SifraMagacina", "SifraArtikla");

                    b.ToTable("MaterijalneKartice");
                });

            modelBuilder.Entity("AccountingData.Models.MestoTroska", b =>
                {
                    b.Property<int>("MestoTroskaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAktivno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("MestoTroskaId");

                    b.ToTable("MestaTroska");
                });

            modelBuilder.Entity("AccountingData.Models.Nalog", b =>
                {
                    b.Property<int>("NalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumKnjiženja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNaloga")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VrstaNaloga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("NalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("Nalozi");
                });

            modelBuilder.Entity("AccountingData.Models.NalogAudit", b =>
                {
                    b.Property<int>("NalogAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Akcija")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Vreme")
                        .HasColumnType("TEXT");

                    b.HasKey("NalogAuditId");

                    b.HasIndex("NalogId");

                    b.ToTable("NalogAuditi");
                });

            modelBuilder.Entity("AccountingData.Models.NarudzbenicaDobavljacu", b =>
                {
                    b.Property<int>("NarudzbenicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojNarudzbenice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivDobavljaca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RokIsporuke")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoNeto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoPdv")
                        .HasColumnType("TEXT");

                    b.HasKey("NarudzbenicaId");

                    b.ToTable("NarudzbeniceDobavljacima");
                });

            modelBuilder.Entity("AccountingData.Models.NarudzbenicaStavka", b =>
                {
                    b.Property<int>("NarudzbenicaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosNeto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KolicinaNarucena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KolicinaPristigla")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NarudzbenicaDobavljacuNarudzbenicaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NarudzbenicaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivArtikla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PdvStopa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NarudzbenicaStavkaId");

                    b.HasIndex("NarudzbenicaDobavljacuNarudzbenicaId");

                    b.ToTable("NarudzbeniceStavke");
                });

            modelBuilder.Entity("AccountingData.Models.NivelacijaCena", b =>
                {
                    b.Property<int>("NivelacijaCenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNivelacije")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumNivelacije")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoRazlika")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("NivelacijaCenaId");

                    b.HasIndex("MagacinId");

                    b.HasIndex("NalogId");

                    b.ToTable("NivelacijeCena");
                });

            modelBuilder.Entity("AccountingData.Models.NivelacijaStavka", b =>
                {
                    b.Property<int>("NivelacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KolicinaZaliha")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("NivelacijaCenaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NovaCena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RazlikaPoJedinici")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StaraCena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnaRazlika")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("NivelacijaStavkaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("NivelacijaCenaId");

                    b.ToTable("NivelacijaStavke");
                });

            modelBuilder.Entity("AccountingData.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraPartnera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.HasIndex("SifraPartnera");

                    b.ToTable("Partneri");
                });

            modelBuilder.Entity("AccountingData.Models.PonudaPredracun", b =>
                {
                    b.Property<int>("PonudaPredracunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RacunOtpremnicaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RokVazenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoNeto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoPdv")
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaDokumenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PonudaPredracunId");

                    b.ToTable("PonudePredracuni");
                });

            modelBuilder.Entity("AccountingData.Models.PonudaStavka", b =>
                {
                    b.Property<int>("PonudaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosNeto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivArtikla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PdvStopa")
                        .HasColumnType("TEXT");

                    b.Property<int>("PonudaPredracunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RabatProcenat")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PonudaStavkaId");

                    b.HasIndex("PonudaPredracunId");

                    b.ToTable("PonudeStavke");
                });

            modelBuilder.Entity("AccountingData.Models.PoreskaTarifa", b =>
                {
                    b.Property<int>("PoreskaTarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorezProcenat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("PorezUCeni")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PosebanPorezProcenat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TarifniBroj")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("PoreskaTarifaId");

                    b.HasIndex("TarifniBroj")
                        .IsUnique();

                    b.ToTable("PoreskeTarife");
                });

            modelBuilder.Entity("AccountingData.Models.PrimopredajaNalog", b =>
                {
                    b.Property<int>("PrimopredajaNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacinaDaje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaPrima")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaDokumenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("PrimopredajaNalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("PrimopredajaNalozi");
                });

            modelBuilder.Entity("AccountingData.Models.PrimopredajaStavka", b =>
                {
                    b.Property<int>("PrimopredajaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PrimopredajaNalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PrimopredajaStavkaId");

                    b.HasIndex("PrimopredajaNalogId");

                    b.ToTable("PrimopredajaStavke");
                });

            modelBuilder.Entity("AccountingData.Models.Promena", b =>
                {
                    b.Property<int>("PromenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sifra")
                        .HasColumnType("INTEGER");

                    b.HasKey("PromenaId");

                    b.HasIndex("Sifra");

                    b.ToTable("Promene");
                });

            modelBuilder.Entity("AccountingData.Models.PutniNalog", b =>
                {
                    b.Property<int>("PutniNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Akontacija")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BrojDnevnica")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPolaska")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPovratka")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IznosDnevniceRsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevoznoSredstvo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RadnoMesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relacija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SvrhaPutovanja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TrajanjeSati")
                        .HasColumnType("REAL");

                    b.Property<decimal>("TroskoviGoriva")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TroskoviPrevoza")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TroskoviSmestaja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoDnevnice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoZaIsplatu")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vrsta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZaposleniIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PutniNalogId");

                    b.ToTable("PutniNalozi");
                });

            modelBuilder.Entity("AccountingData.Models.PutniNalogTrosakStavka", b =>
                {
                    b.Property<int>("PutniNalogTrosakStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PutniNalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaTroska")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PutniNalogTrosakStavkaId");

                    b.HasIndex("PutniNalogId");

                    b.ToTable("PutniNaloziTroskoviStavke");
                });

            modelBuilder.Entity("AccountingData.Models.RacunOtpremnica", b =>
                {
                    b.Property<int>("RacunOtpremnicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojOtpremnice")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiskalniBroj")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FiskalniDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiskalniQrKod")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FiskalniStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontoKupca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NacinPlacanja")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RokPlacanja")
                        .HasColumnType("TEXT");

                    b.Property<int>("RokPlacanjaDana")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RokVazenjaPredracuna")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SefDatumSlanja")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SefPoruka")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SefStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipDokumenta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UkupnoOsnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoRabat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoZaUplatu")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("RacunOtpremnicaId");

                    b.HasIndex("MagacinId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("RacuniOtpremnice");
                });

            modelBuilder.Entity("AccountingData.Models.RacunOtpremnicaStavka", b =>
                {
                    b.Property<int>("RacunOtpremnicaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatProcenat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RacunOtpremnicaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopaPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("RacunOtpremnicaStavkaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("RacunOtpremnicaId");

                    b.ToTable("RacunOtpremnicaStavke");
                });

            modelBuilder.Entity("AccountingData.Models.StavkaNaloga", b =>
                {
                    b.Property<int>("StavkaNalogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DevizniDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DevizniPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("KursValute")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("MestoTroskaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PromenaKod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValutaDospela")
                        .HasColumnType("TEXT");

                    b.HasKey("StavkaNalogaId");

                    b.HasIndex("MestoTroskaId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("StavkeNaloga");
                });

            modelBuilder.Entity("AccountingData.Models.TrebovanjeNalog", b =>
                {
                    b.Property<int>("TrebovanjeNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TrebovanjeNalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("TrebovanjeNalozi");
                });

            modelBuilder.Entity("AccountingData.Models.TrebovanjeStavka", b =>
                {
                    b.Property<int>("TrebovanjeStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("KontoTroska")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrebovanjeNalogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrebovanjeStavkaId");

                    b.HasIndex("TrebovanjeNalogId");

                    b.ToTable("TrebovanjeStavke");
                });

            modelBuilder.Entity("AccountingData.Models.UlazNalog", b =>
                {
                    b.Property<int>("UlazNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UlazNalogId");

                    b.HasIndex("BrojNaloga");

                    b.ToTable("UlazNalozi");
                });

            modelBuilder.Entity("AccountingData.Models.UlazStavka", b =>
                {
                    b.Property<int>("UlazStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UlazNalogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UlazStavkaId");

                    b.HasIndex("UlazNalogId");

                    b.ToTable("UlazStavke");
                });

            modelBuilder.Entity("AccountingData.Models.UvoznaKalkulacija", b =>
                {
                    b.Property<int>("UvoznaKalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKalkulacije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarinaRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DatumInoFakture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKalkulacije")
                        .HasColumnType("TEXT");

                    b.Property<string>("InoBrojFakture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InoPartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KursValute")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OstaliZavisniTroskoviRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrevozRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SpedicijaRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnaNabavnaVrednostRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoDevize")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoFakturaRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("UvoznaKalkulacijaId");

                    b.HasIndex("InoPartnerId");

                    b.HasIndex("MagacinId");

                    b.ToTable("UvozneKalkulacije");
                });

            modelBuilder.Entity("AccountingData.Models.UvoznaStavka", b =>
                {
                    b.Property<int>("UvoznaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarinaIznosRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CarinaProcenat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InoCenaDevize")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("InoIznosDevize")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InoIznosRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NabavnaCenaPoJediniciRsd")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("RasporedjeniZavisniTroskoviRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnaNabavnaVrednostRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UvoznaKalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UvoznaStavkaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("UvoznaKalkulacijaId");

                    b.ToTable("UvozneStavke");
                });

            modelBuilder.Entity("AccountingData.Models.ZatvaranjeStavke", b =>
                {
                    b.Property<int>("ZatvaranjeStavkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZatvaranja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("StavkaDugujeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StavkaPotrazujeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaZatvaranja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ZatvaranjeStavkeId");

                    b.HasIndex("StavkaDugujeId");

                    b.HasIndex("StavkaPotrazujeId");

                    b.ToTable("ZatvaranjaStavki");
                });

            modelBuilder.Entity("AccountingData.Models.DokumentPrilog", b =>
                {
                    b.HasOne("AccountingData.Models.Kalkulacija", "Kalkulacija")
                        .WithMany()
                        .HasForeignKey("KalkulacijaId");

                    b.HasOne("AccountingData.Models.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.HasOne("AccountingData.Models.RacunOtpremnica", "RacunOtpremnica")
                        .WithMany()
                        .HasForeignKey("RacunOtpremnicaId");

                    b.Navigation("Kalkulacija");

                    b.Navigation("Nalog");

                    b.Navigation("RacunOtpremnica");
                });

            modelBuilder.Entity("AccountingData.Models.KalkulacijaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.Kalkulacija", "Kalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("KalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalkulacija");
                });

            modelBuilder.Entity("AccountingData.Models.KompenzacijaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.Kompenzacija", "Kompenzacija")
                        .WithMany("Stavke")
                        .HasForeignKey("KompenzacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kompenzacija");
                });

            modelBuilder.Entity("AccountingData.Models.MaloprodajnaKalkulacijaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.MaloprodajnaKalkulacija", "MaloprodajnaKalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("MaloprodajnaKalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaloprodajnaKalkulacija");
                });

            modelBuilder.Entity("AccountingData.Models.NarudzbenicaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.NarudzbenicaDobavljacu", "NarudzbenicaDobavljacu")
                        .WithMany("Stavke")
                        .HasForeignKey("NarudzbenicaDobavljacuNarudzbenicaId");

                    b.Navigation("NarudzbenicaDobavljacu");
                });

            modelBuilder.Entity("AccountingData.Models.NivelacijaCena", b =>
                {
                    b.HasOne("AccountingData.Models.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId");

                    b.HasOne("AccountingData.Models.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.Navigation("Magacin");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("AccountingData.Models.NivelacijaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId");

                    b.HasOne("AccountingData.Models.NivelacijaCena", "NivelacijaCena")
                        .WithMany("Stavke")
                        .HasForeignKey("NivelacijaCenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("NivelacijaCena");
                });

            modelBuilder.Entity("AccountingData.Models.PonudaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.PonudaPredracun", "PonudaPredracun")
                        .WithMany("Stavke")
                        .HasForeignKey("PonudaPredracunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PonudaPredracun");
                });

            modelBuilder.Entity("AccountingData.Models.PrimopredajaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.PrimopredajaNalog", "PrimopredajaNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("PrimopredajaNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimopredajaNalog");
                });

            modelBuilder.Entity("AccountingData.Models.PutniNalogTrosakStavka", b =>
                {
                    b.HasOne("AccountingData.Models.PutniNalog", "PutniNalog")
                        .WithMany("StavkeTroskova")
                        .HasForeignKey("PutniNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PutniNalog");
                });

            modelBuilder.Entity("AccountingData.Models.RacunOtpremnica", b =>
                {
                    b.HasOne("AccountingData.Models.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId");

                    b.HasOne("AccountingData.Models.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.HasOne("AccountingData.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Magacin");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("AccountingData.Models.RacunOtpremnicaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId");

                    b.HasOne("AccountingData.Models.RacunOtpremnica", "RacunOtpremnica")
                        .WithMany("Stavke")
                        .HasForeignKey("RacunOtpremnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("RacunOtpremnica");
                });

            modelBuilder.Entity("AccountingData.Models.StavkaNaloga", b =>
                {
                    b.HasOne("AccountingData.Models.MestoTroska", "MestoTroska")
                        .WithMany()
                        .HasForeignKey("MestoTroskaId");

                    b.HasOne("AccountingData.Models.Nalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingData.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("MestoTroska");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("AccountingData.Models.TrebovanjeStavka", b =>
                {
                    b.HasOne("AccountingData.Models.TrebovanjeNalog", "TrebovanjeNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("TrebovanjeNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrebovanjeNalog");
                });

            modelBuilder.Entity("AccountingData.Models.UlazStavka", b =>
                {
                    b.HasOne("AccountingData.Models.UlazNalog", "UlazNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("UlazNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UlazNalog");
                });

            modelBuilder.Entity("AccountingData.Models.UvoznaKalkulacija", b =>
                {
                    b.HasOne("AccountingData.Models.Partner", "InoPartner")
                        .WithMany()
                        .HasForeignKey("InoPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingData.Models.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InoPartner");

                    b.Navigation("Magacin");
                });

            modelBuilder.Entity("AccountingData.Models.UvoznaStavka", b =>
                {
                    b.HasOne("AccountingData.Models.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingData.Models.UvoznaKalkulacija", "UvoznaKalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("UvoznaKalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("UvoznaKalkulacija");
                });

            modelBuilder.Entity("AccountingData.Models.ZatvaranjeStavke", b =>
                {
                    b.HasOne("AccountingData.Models.StavkaNaloga", "StavkaDuguje")
                        .WithMany()
                        .HasForeignKey("StavkaDugujeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingData.Models.StavkaNaloga", "StavkaPotrazuje")
                        .WithMany()
                        .HasForeignKey("StavkaPotrazujeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StavkaDuguje");

                    b.Navigation("StavkaPotrazuje");
                });

            modelBuilder.Entity("AccountingData.Models.Kalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.Kompenzacija", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.MaloprodajnaKalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.Nalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.NarudzbenicaDobavljacu", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.NivelacijaCena", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.PonudaPredracun", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.PrimopredajaNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.PutniNalog", b =>
                {
                    b.Navigation("StavkeTroskova");
                });

            modelBuilder.Entity("AccountingData.Models.RacunOtpremnica", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.TrebovanjeNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.UlazNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("AccountingData.Models.UvoznaKalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
